---
- hosts: webserver
  sudo: false
  user: jewilmeer

  vars_files:
    - ../variables/global.yml
    - ../variables/tvguide.yml

  vars:
    home: /home/$user
    webroot: $home/www
    domain: jewilmeer
    application_path: $webroot/$domain

  tasks:
    - name: 'checkout latest version of application'
      git: repo=git@github.com:jewilmeer/tv-guide.git dest=$application_path version=master

    - name: bundle
      shell: "chdir=$application_path bundle install --deployment --binstubs --without development test"

    - name: stop sidekiq
      service: name=sidekiq state=stopped
      sudo: true

    - name: prepare assets
      shell: "chdir=$application_path bundle exec rake assets:precompile"
      ignore_errors: True #skip if existing

    - name: copy database config
      template: src=../templates/database.yml.tmpl dest=$application_path/config/database.yml

    - name: migrate
      shell: "chdir=$application_path RAILS_ENV=production bundle exec rake db:migrate"

    - name: restart nginx
      shell: "chdir=$application_path touch tmp/restart.txt"
      notify: restart sidekiq

  handlers:
    - name: restart sidekiq
      service: name=sidekiq state=restarted
      sudo: true
