---
- hosts: webserver
  sudo: false
  user: jewilmeer
  gather_facts: false

  vars:
    home: /home/$user
    ruby_version: "1.9.3-p374"
    ruby_bin_path: /home/$user/.rbenv/shims
    rbenv_exec: /home/$user/.rbenv/bin/rbenv

  vars_files:
    - ../variables/global.yml
    - ../variables/tvguide.yml
  tasks:
    - name: 'install brightbox deb repositories'
      apt_repository: repo=ppa:brightbox/ruby-ng
      sudo: true

    - name: 'Install required apt packages'
      apt: pkg=$item state=installed update_cache=yes
      sudo: true
      with_items:
        - ruby1.9.3
        - ruby-switch
        - nginx-full
        - libxml2-dev
        - libxslt1-dev
        - postgresql-9.1
        - postgresql-client-9.1
        - postgresql-server-dev-9.1

    - name: create db user
      sudo: true
      action: shell sudo -u postgres psql -c "CREATE ROLE jewilmeer WITH SUPERUSER CREATEDB LOGIN password '$pg_password';"
      ignore_errors: True #skip if existing

    - name: create db user
      sudo: true
      action: shell sudo -u postgres psql -c "CREATE ROLE $pg_user WITH SUPERUSER CREATEDB LOGIN password '$pg_password';"
      ignore_errors: True #skip if existing

    - name: gem, could you stop making docs
      shell: 'echo "gem: --no-rdoc --no-ri" >> $home/.gemrc'

    - gem: name=rack state=present version=1.4.5
      sudo: true

    - name: install basic gems
      gem: name=$item state=present
      with_items:
      - bundler
      - passenger
      - therubyracer
      sudo: true
      notify: restart nginx

    - name: remove default nginx site
      file: path=/etc/nginx/sites-enabled/default state=absent
      sudo: true
      notify: restart nginx

    - name: set config files for nginx
      copy: src=../files/$item dest=/etc/nginx/conf.d/$item
      with_items:
        - passenger.conf
        - nginx.conf
      sudo: true
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
      sudo: true

# inspired by https://github.com/tobyhede/ansible-centos-rails-nginx-passenger/blob/master/ruby.yml